import { Titillium_Web } from "next/font/google";
import "./globals.css";

const titillium_web = Titillium_Web({
  subsets: ['latin'],
  weight: ["300", "400", "600", "700", "900"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={titillium_web.className}>{children}</body>
    </html>
  );
}
